-- MySQL Script generated by MySQL Workbench
-- Thu Feb 25 17:37:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_Saldo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_Saldo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_Saldo` DEFAULT CHARACTER SET utf8 ;
USE `DB_Saldo` ;

-- -----------------------------------------------------
-- Table `DB_Saldo`.`mediosdepagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Saldo`.`mediosdepagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Saldo`.`coeficiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Saldo`.`coeficiente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mediosdepagos1` INT NOT NULL,
  `mediosdepagos2` INT NOT NULL,
  `coeficiente` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `id_nombre_idx` (`mediosdepagos1` ASC),
  INDEX `id_nombre2_idx` (`mediosdepagos2` ASC),
  CONSTRAINT `id_nombre`
    FOREIGN KEY (`mediosdepagos1`)
    REFERENCES `DB_Saldo`.`mediosdepagos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_nombre2`
    FOREIGN KEY (`mediosdepagos2`)
    REFERENCES `DB_Saldo`.`mediosdepagos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
